[2025-04-25 19:45:22,750][jax._src.callback][ERROR] - jax.io_callback failed
Traceback (most recent call last):
  File "/home/aryaman/anaconda3/envs/cheap/lib/python3.11/site-packages/jax/_src/callback.py", line 436, in io_callback_impl
    return tree_util.tree_map(np.asarray, callback(*args))
                                          ^^^^^^^^^^^^^^^
  File "/home/aryaman/anaconda3/envs/cheap/lib/python3.11/site-packages/jax/_src/callback.py", line 73, in __call__
    return tree_util.tree_leaves(self.callback_func(*args, **kwargs))
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aryaman/Desktop/project-cheap/cheap_talk/cheap_talk/src/jax_experiments/smax/k2mappo/k2mappo_rnn_smax.py", line 256, in callback
    LOGGER.log({seed: metric})
               ^^^^^^^^^^^^^^
TypeError: unhashable type: 'jaxlib.xla_extension.ArrayImpl'
